apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-app-deployment
spec:
  selector:
    matchLabels:
      app: shop-app
  replicas: 1
  template:
    metadata:
      labels:
        app: shop-app
    spec:
      containers:
        - name: shop-app
          image: shop-app
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
